# Generated by Django 6.0.4 on 2026-05-21 04:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('type', models.CharField(default='news', help_text='Например: tournament, training, scrim, news', max_length=100, verbose_name='Тип объявления')),
                ('date', models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Дата публикации')),
                ('content', models.TextField(verbose_name='Содержимое (текст)')),
                ('countdown_date', models.DateTimeField(blank=True, help_text='Если указано, на сайте будет тикать таймер', null=True, verbose_name='Время окончания (для таймера обратного отсчета)')),
                ('author', models.CharField(max_length=100, verbose_name='Автор публикации')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='announcements/', verbose_name='Медиафайл (Фото или Видео)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Новость и объявление',
                'verbose_name_plural': 'Новости и объявления',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_name', models.CharField(default='', max_length=100, verbose_name='Название клана')),
                ('clan_tag', models.CharField(default='', max_length=20, verbose_name='Тэг клана')),
                ('clan_founded', models.CharField(default='', max_length=10, verbose_name='Год основания')),
                ('hero_title_1', models.CharField(default='', max_length=100, verbose_name='Первая строка заголовка')),
                ('hero_title_2', models.CharField(default='', max_length=100, verbose_name='Вторая строка заголовка')),
                ('hero_description', models.TextField(default='', verbose_name='Описание на главной')),
                ('hero_background_type', models.CharField(choices=[('image', 'Картинка (Фото)'), ('video', 'Видео')], default='video', max_length=20, verbose_name='Тип фона на главной')),
                ('hero_background_file', models.FileField(blank=True, null=True, upload_to='hero_backgrounds/', verbose_name='Файл фона на главной (mp4 / jpg / png)')),
                ('discord_link', models.CharField(default='', max_length=255, verbose_name='Ссылка Discord')),
                ('telegram_link', models.CharField(default='', max_length=255, verbose_name='Ссылка Telegram @username')),
                ('stats_tournaments_title', models.CharField(default='', max_length=50, verbose_name='Статистика 1: Заголовок')),
                ('stats_tournaments_value', models.CharField(default='', max_length=50, verbose_name='Статистика 1: Значение')),
                ('stats_tournaments_desc', models.CharField(default='', max_length=100, verbose_name='Статистика 1: Подпись')),
                ('stats_rank_title', models.CharField(default='', max_length=50, verbose_name='Статистика 2: Заголовок')),
                ('stats_rank_value', models.CharField(default='', max_length=50, verbose_name='Статистика 2: Значение')),
                ('stats_rank_desc', models.CharField(default='', max_length=100, verbose_name='Статистика 2: Подпись')),
                ('stats_members_title', models.CharField(default='', max_length=50, verbose_name='Статистика 3: Заголовок')),
                ('stats_members_value', models.CharField(default='', max_length=50, verbose_name='Статистика 3: Значение')),
                ('stats_members_desc', models.CharField(default='', max_length=100, verbose_name='Статистика 3: Подпись')),
                ('stats_experience_title', models.CharField(default='', max_length=50, verbose_name='Статистика 4: Заголовок')),
                ('stats_experience_value', models.CharField(default='', max_length=50, verbose_name='Статистика 4: Значение')),
                ('stats_experience_desc', models.CharField(default='', max_length=100, verbose_name='Статистика 4: Подпись')),
                ('rules_terms_desc', models.TextField(default='', verbose_name='Сноска в правилах рекрутинга')),
            ],
            options={
                'verbose_name': 'Общие настройки сайта',
                'verbose_name_plural': 'Общие настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='ClanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100, verbose_name='Раздел / Категория')),
                ('title', models.CharField(max_length=255, verbose_name='Название правила')),
                ('content', models.TextField(verbose_name='Содержание правила')),
                ('severity', models.CharField(choices=[('low', 'Низкая (Предупреждение)'), ('medium', 'Средняя (Выговор)'), ('high', 'Высокая (Исключение)')], default='medium', max_length=20, verbose_name='Важность нарушения')),
            ],
            options={
                'verbose_name': 'Правило клана',
                'verbose_name_plural': 'Свод правил клана',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HeroBackgroundSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_type', models.CharField(choices=[('image', 'Фото (Картинка)'), ('video', 'Видео (без звука)')], default='image', max_length=20, verbose_name='Тип слайда')),
                ('file', models.FileField(upload_to='hero_carousel/', verbose_name='Файл слайда (mp4 / jpg / png / webp)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Слайд фона на главной',
                'verbose_name_plural': 'Карусель фона на главной',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Никнейм игрока')),
                ('device', models.CharField(max_length=150, verbose_name='Игровое устройство')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень аккаунта')),
                ('kd', models.FloatField(blank=True, null=True, verbose_name='K/D Ratio (необязательно)')),
                ('signature_weapon', models.CharField(default='', max_length=150, verbose_name='Любимое оружие')),
                ('avatar_file', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка игрока (Файл фото)')),
                ('profile_file', models.FileField(blank=True, null=True, upload_to='player_profiles/', verbose_name='Полноэкранное медиа профиля (Файл фото или видео)')),
                ('achievements', models.TextField(help_text='Введите каждое достижение с новой строки', verbose_name='Достижения')),
                ('region', models.CharField(default='', max_length=150, verbose_name='Регион')),
                ('joined_date', models.CharField(max_length=100, verbose_name='Когда присоединился')),
            ],
            options={
                'verbose_name': 'Игрок (Ростер)',
                'verbose_name_plural': 'Состав (Ростер)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название роли (например: Капитан, Атакующий, Снайпер)')),
            ],
            options={
                'verbose_name': 'Роль игрока',
                'verbose_name_plural': 'Роли игроков',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('game_id', models.CharField(max_length=100, verbose_name='PUBG ID')),
                ('role', models.CharField(max_length=100, verbose_name='Игровая роль')),
                ('device', models.CharField(max_length=150, verbose_name='Игровое устройство')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('play_time', models.PositiveIntegerField(verbose_name='Часов в игре в день')),
                ('discord_telegram', models.CharField(max_length=200, verbose_name='Discord / Telegram')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе / Опыт')),
                ('assessment_grade', models.CharField(choices=[('unqualified', 'Резерв (Отказ)'), ('accepted_with_test', 'Допущен к дуэли (1v1 тест)'), ('excellent', 'Высокий приоритет (PRO)')], max_length=50, verbose_name='Автоматический статус отбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Заявка на вступление',
                'verbose_name_plural': 'Заявки на вступление (Рекруты)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('type', models.CharField(default='scrim', help_text='Например: scrim, training, tournament, meeting и т.д.', max_length=100, verbose_name='Тип события')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время проведения (UTC)')),
                ('team_size', models.CharField(default='', max_length=100, verbose_name='Тип игры / Формат сбора')),
                ('prize_pool', models.CharField(blank=True, max_length=150, null=True, verbose_name='Призовой фонд (необязательно)')),
                ('slots_filled', models.PositiveIntegerField(default=0, verbose_name='Заполнено слотов / участников')),
                ('slots_total', models.PositiveIntegerField(default=16, verbose_name='Всего слотов / участников')),
                ('opponent', models.CharField(blank=True, max_length=200, null=True, verbose_name='Противник (необязательно)')),
            ],
            options={
                'verbose_name': 'Событие расписания',
                'verbose_name_plural': 'Расписание событий',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', 'Видео-хайлайт'), ('screenshot', 'Скриншот матча'), ('trophy', 'Кубок / Награда')], default='screenshot', max_length=100, verbose_name='Тип медиа')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(default='', max_length=100, verbose_name='Категория')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='gallery/', verbose_name='Загрузить медиафайл напрямую')),
                ('thumbnail_upload', models.ImageField(blank=True, null=True, upload_to='gallery/thumbs/', verbose_name='Загрузить файл обложки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание хайлайта (необязательное)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('date', models.CharField(blank=True, default='', max_length=100, verbose_name='Дата добавления')),
                ('author', models.CharField(blank=True, default='Администрация', max_length=100, verbose_name='Кто загрузил')),
                ('tagged_players', models.ManyToManyField(blank=True, related_name='gallery_items', to='api.player', verbose_name='Отмеченные участники клана')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Галерея медиа',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.playerrole', verbose_name='Роль игрока'),
        ),
    ]
