# Generated by Django 6.0.4 on 2026-05-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanconfig',
            name='recruitment_image',
            field=models.ImageField(blank=True, null=True, upload_to='recruitment/', verbose_name='Изображение на форме подачи заявки (PUBG фото)'),
        ),
        migrations.AddField(
            model_name='recruitmentsubmission',
            name='stat_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='recruits_stats/', verbose_name='Фото статистики 1'),
        ),
        migrations.AddField(
            model_name='recruitmentsubmission',
            name='stat_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='recruits_stats/', verbose_name='Фото статистики 2'),
        ),
        migrations.AddField(
            model_name='recruitmentsubmission',
            name='stat_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='recruits_stats/', verbose_name='Фото статистики 3'),
        ),
        migrations.AddField(
            model_name='recruitmentsubmission',
            name='stat_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='recruits_stats/', verbose_name='Фото статистики 4'),
        ),
    ]
