# Generated by Django 6.0.4 on 2026-05-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clanconfig_recruitment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanconfig',
            name='rules_image',
            field=models.ImageField(blank=True, null=True, upload_to='rules/', verbose_name='Изображение над Уставом/Правилами (PUBG фото)'),
        ),
    ]
