# Generated by Django 6.0.4 on 2026-05-21 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clanconfig_rules_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание игрока (необязательно)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='device',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Игровое устройство (необязательно)'),
        ),
        migrations.CreateModel(
            name='PlayerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='player_media/', verbose_name='Файл медиа (Фото или Видео)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_gallery', to='api.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Медиафайл игрока',
                'verbose_name_plural': 'Дополнительные медиафайлы игрока',
            },
        ),
    ]
