# Generated by Django 6.0.4 on 2026-05-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player_description_alter_player_device_playermedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Игровой UID (PUBG Mobile ID) (необязательно)'),
        ),
    ]
