# Generated by Django 6.0.4 on 2026-05-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_player_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clan_role',
            field=models.CharField(choices=[('leader', 'Лидер'), ('deputy', 'Заместитель (Зам)'), ('elite', 'Элита'), ('member', 'Член клана')], default='member', max_length=50, verbose_name='Роль/Статус в клане'),
        ),
    ]
