# Generated by Django 6.0.4 on 2026-05-21 07:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_player_clan_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='gallery/', validators=[api.models.validate_file_size], verbose_name='Загрузить медиафайл напрямую'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='thumbnail_upload',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbs/', validators=[api.models.validate_file_size], verbose_name='Загрузить файл обложки'),
        ),
        migrations.AlterField(
            model_name='herobackgroundslide',
            name='file',
            field=models.FileField(upload_to='hero_carousel/', validators=[api.models.validate_file_size], verbose_name='Файл слайда (mp4 / jpg / png / webp)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[api.models.validate_file_size], verbose_name='Аватарка игрока (Файл фото)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_file',
            field=models.FileField(blank=True, null=True, upload_to='player_profiles/', validators=[api.models.validate_file_size], verbose_name='Полноэкранное медиа профиля (Файл фото или видео)'),
        ),
        migrations.AlterField(
            model_name='playermedia',
            name='file',
            field=models.FileField(upload_to='player_media/', validators=[api.models.validate_file_size], verbose_name='Файл медиа (Фото или Видео)'),
        ),
        migrations.AlterField(
            model_name='recruitmentsubmission',
            name='stat_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='recruits_stats/', validators=[api.models.validate_file_size], verbose_name='Фото статистики 1'),
        ),
        migrations.AlterField(
            model_name='recruitmentsubmission',
            name='stat_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='recruits_stats/', validators=[api.models.validate_file_size], verbose_name='Фото статистики 2'),
        ),
        migrations.AlterField(
            model_name='recruitmentsubmission',
            name='stat_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='recruits_stats/', validators=[api.models.validate_file_size], verbose_name='Фото статистики 3'),
        ),
        migrations.AlterField(
            model_name='recruitmentsubmission',
            name='stat_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='recruits_stats/', validators=[api.models.validate_file_size], verbose_name='Фото статистики 4'),
        ),
    ]
