# Generated by Django 6.0.5 on 2026-05-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_galleryitem_file_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрено (Показывается на сайте)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID автора'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрено (Показывается на сайте)'),
        ),
        migrations.AddField(
            model_name='player',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID игрока'),
        ),
    ]
