# Generated by Django 6.0.4 on 2026-05-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_galleryitem_is_approved_galleryitem_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Игрок (Ростер)', 'verbose_name_plural': 'Состав (Ростер)'},
        ),
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки (Позиция)'),
        ),
    ]
