# Generated by Django 6.0.4 on 2026-05-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_player_user_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='clan_role',
            field=models.CharField(choices=[('leader', 'Лидер Клана'), ('deputy', 'Заместитель Клана'), ('elite', 'Элита Клана'), ('member', 'Член Клана')], default='member', max_length=50, verbose_name='Роль/Статус в клане'),
        ),
    ]
