# Generated by Django 6.0.5 on 2026-05-28 06:49

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_player_clan_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
            ],
            options={
                'verbose_name': 'Пользователь (Зарегистрирован через бот)',
                'verbose_name_plural': '👥 Пользователи (Зарегистрированы через бот)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
